version: "3"
services: 
 wordpress:
  image: wordpress
  ports:
   - "8080:80"
  depends_on:
   - mysql
  environment:
   WORDPRESS_DB_HOST: mysql
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: "test123"
   WORDPRESS_DB_NAME: website
 mysql:
  image: "mysql:5.7"
  environment: 
   MYSQL_DATABASE: website
   MYSQL_ROOT_PASSWORD: "test123"


